site_name: 'Halledersiniz - Arduino01'
site_url: https://ogren.halledersiniz.com/arduino01/
repo_url: https://github.com/cemkod/hallederiz_arduino01_docs
site_description: 'Halledersiniz - Arduino01'
site_author: 'Halledersiniz'
copyright: 'Copyright &copy; 2025 Halledersiniz'


theme:
  name: material
  language: tr
  logo: assets/images/halledersiniz-logo.png
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
  custom_dir: overrides

nav:
  - Giriş: giris.md
  - Arduino IDE Kurulumu:
    - Windows: windows-kurulum.md
    - macOS: macos-kurulum.md
    - Linux: linux-kurulum.md

  - Proje 01 - LED: 01-LED.md
  - Proje 02 - Buton: 02-buton.md
  - Proje 03 - Seri iletişim: 03-seri-iletisim.md
  - Proje 04 - Potansiyometre: 04-pot.md
  - Proje 05 - Müzik Kutusu: 05-buzzer.md
  - Proje 06 - Teremin: 06-teremin.md
  - Servo sıfırlama: servo-sifirlama.md
  - Proje 07 - Araba Simülasyonu: 07-araba-simulasyonu.md
  - Proje 08 - LCD Demo Animasyonu: 08-demo.md
  - Proje 09 - Termostat: 09-termometre.md
  - Proje 10 - Dijital Su Terazisi: 10-dijital-su-terazisi.md
  - Proje 11 - Sinirmatik: 11-sinirmatik.md
  - Proje 12 - Akıllı Alarm Sistemi: 12-alarm-sistemi.md
  - Buradan Nereye?: buradan-nereye.md

  - Arduinoya Nasıl Kod Yüklerim?: kod-yukleme.md
  - Kütüphane Kurma: kutuphane-kurma.md
  - Sorun Giderme: sorun-giderme.md
  - Modül Listesi: modul-listesi.md
  - Kumanda Kodları: kumanda-kodlari.md
  - Bileşenler:
    - LED: k01_led.md


extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - footnotes
  - admonition
  - def_list
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative  # Relative to the current Markdown file
  - pymdownx.superfences  
  - pymdownx.tasklist:
      custom_checkbox: true
