site_name: 'Arduino01 Hepsi Bir Arada Başlangıç Seti'
site_url: https://ogren.halledersiniz.com/arduino01/
repo_url: https://github.com/cemkod/hallederiz_arduino01_docs
site_description: 'Halledersiniz Arduino01 Hepsi bir Arada Başlangıç Seti için Dersler'
site_author: 'Halledersiniz'
copyright: 'Copyright &copy; 2025 Halledersiniz'


theme:
  name: material
  language: tr
  features:
    - content.code.copy

nav:
  - Giriş: giris.md
  - Modül Listesi: modul-listesi.md
  - Kurulum:
    - Linux: linux-kurulum.md
  - Bileşenler:
    - LED: k01_led.md
  - Proje 01 - LED: 01-LED.md
  - Proje 02 - Buton: 02-buton.md
  - Proje 03 - Seri iletişim: 03-seri-iletisim.md
  - Proje 04 - Potansiyometre: 04-pot.md
  - Proje 05 - Buzzer: 05-buzzer.md
  - Proje 06 - Mesafe Sensörü: 06-mesafe-sensoru.md
  - Proje 07 - Araba Simulasyonu: 07-araba-simulasyonu.md
  - Proje 08 - LCD Demo Animasyonu: 08-demo.md
  - Proje 09 - Sıcaklık ve Nem Sensörü: 09-termometre.md

  - Sorun Giderme: sorun-giderme.md


markdown_extensions:
  - footnotes
  - admonition
  - def_list
  - pymdownx.highlight:
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: !relative  # Relative to the current Markdown file
  - pymdownx.superfences  
  - pymdownx.tasklist:
      custom_checkbox: true
